---
include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - example/lib/src/**
    - example/lib/main.dart

linter:
  rules:
    always_specify_types: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    literal_only_boolean_expressions: true
    sort_constructors_first: true
    sort_pub_dependencies: false
    public_member_api_docs: true