name: dynamic_cached_fonts
description: A customizable dynamic font loader for flutter with caching enabled.
version: 0.0.1

environment:
  sdk: ">=2.11.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ^5.0.0
  flutter_cache_manager: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.3.0

flutter: null
