name: Code Analysis
on: [push, pull_request]

jobs:
  pana_analyze:
    name: Analyze package with Pana
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: beta

      - run: flutter pub get

      - name: Activate pana
        run: flutter pub global activate pana

      - name: Run pana
        run: flutter pub global run pana . --no-warning
